import { MigrationInterface, QueryRunner } from "typeorm";

export class AddActivityLogMetadata1783455366469 implements MigrationInterface {
    name = 'AddActivityLogMetadata1783455366469'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_state_exhibits_workbook_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_state_exhibits_state_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_state_exhibits_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cash_settlements_batch_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cash_settlements_reinsurer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cash_settlements_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workbooks_month_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workbooks_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workbooks_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_permissions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_permissions_module_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_permissions_submodule_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_permissions_permission_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_calculation_report_lines_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_calculation_report_lines_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reinsurer_companies_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reinsurer_companies_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carriers_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carriers_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lines_of_business_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lines_of_business_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cob_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cob_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_lob_cobs_treaty_lob_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_lob_cobs_cob_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_lobs_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_lobs_lob_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_state_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_state_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_states_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_states_state_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_mgas_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_mgas_mga_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_broker_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_broker_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_state_carriers_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_state_carriers_risk_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_state_carriers_state_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_state_carriers_broker_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_state_carriers_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_reinsurers_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_reinsurers_reinsurer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_reinsurers_state_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_reinsurers_broker_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaties_mga_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaties_reinsurer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaties_risk_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaties_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaties_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_type_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_type_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_products_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_products_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_products_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_sequence_prefixes_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_sequence_prefixes_sequence_prefix_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_sequence_prefixes_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_itd_totals_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_itd_totals_year"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_itd_totals_month"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_itd_totals_state_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_treaty_itd_totals_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sequence_prefix_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sequence_prefix_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carrier_documents_risk_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carrier_documents_document_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carrier_documents_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_master_lob_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_master_cob_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_state_documents_state_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_state_documents_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_lobs_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_lobs_lob_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_lobs_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_cobs_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_cobs_cob_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_cobs_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_other_names_mga_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_other_names_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_documents_mga_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_documents_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_contact_master_mga_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_contact_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_mga_contact_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_locked_periods_is_locked"`);
        await queryRunner.query(`DROP INDEX "public"."idx_locked_periods_locked_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_document_type_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_document_type_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contact_domain_master_mga_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contact_domain_master_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contact_domain_master_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_broker_documents_broker_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_broker_documents_document_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_broker_documents_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_batches_treaty_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_batches_month_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_batches_workbook_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_batches_state_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_batches_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_batches_period"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_batches_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chart_of_accounts_parent_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chart_of_accounts_earning_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chart_of_accounts_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chart_of_accounts_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entries_batch_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entries_coa_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entries_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_drafts_batch_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_entry_drafts_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gl_mappings_coa_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gl_mappings_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chart_of_account_documents_coa_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chart_of_account_documents_is_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_module_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_submodule_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_entity_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_entity_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_created_at"`);
        await queryRunner.query(`ALTER TABLE "treaty_lob_cobs" DROP CONSTRAINT "uq_treaty_lob_cobs_treaty_lob_id_cob_id"`);
        await queryRunner.query(`ALTER TABLE "treaty_lobs" DROP CONSTRAINT "uq_treaty_lobs_treaty_id_lob_id"`);
        await queryRunner.query(`ALTER TABLE "treaty_states" DROP CONSTRAINT "uq_treaty_states_treaty_id_state_id"`);
        await queryRunner.query(`ALTER TABLE "treaty_mgas" DROP CONSTRAINT "uq_treaty_mgas_treaty_id_mga_id"`);
        await queryRunner.query(`ALTER TABLE "treaty_products" DROP CONSTRAINT "uq_treaty_products_treaty_id_product_id"`);
        await queryRunner.query(`ALTER TABLE "treaty_itd_totals" DROP CONSTRAINT "uq_treaty_itd_totals_treaty_id_state_id_year_month"`);
        await queryRunner.query(`ALTER TABLE "product_lobs" DROP CONSTRAINT "uq_product_lobs_product_id_lob_id"`);
        await queryRunner.query(`ALTER TABLE "product_cobs" DROP CONSTRAINT "uq_product_cobs_product_id_cob_id"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "status" character varying DEFAULT 'success'`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "device" character varying`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "os" character varying`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "browser" character varying`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "session_id" character varying`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "correlation_id" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_1cbdddc932e472bfacf5eb59b8" ON "state_exhibits" ("workbookId") `);
        await queryRunner.query(`CREATE INDEX "IDX_db57e595c744ed4a1da36ce424" ON "state_exhibits" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c2912eb0a6ef3a75578177ac3" ON "state_exhibits" ("isDeleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3c01743a846289d1192f752be" ON "cash_settlements" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab6380bd0d8f038a5ee931ac76" ON "cash_settlements" ("reinsurer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fd56ae8b1051642d5f051c3eb" ON "cash_settlements" ("isDeleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_de92ecfd812c5ce8782c9922d9" ON "workbooks" ("monthKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_95781bd52e5eee5ac8b3e54d67" ON "workbooks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c3f678dd1e8eacf8d39da5913" ON "workbooks" ("isDeleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2cecd1a3531c0b041e29ba46e" ON "users" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd91d7b4b599ee5211d603ccfd" ON "users" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_3495bd31f1862d02931e8e8d2e" ON "user_permissions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ab0433089f0b41a0f8e5b10d1" ON "user_permissions" ("module_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b987cb1236bbe09f8f448ee059" ON "user_permissions" ("submodule_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8145f5fadacd311693c15e41f1" ON "user_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_45bb6d028c873f68369b3e8be8" ON "calculation_report_lines" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3deea0a3e5e072a75d88425dbf" ON "calculation_report_lines" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc99b625341e8f9273fb74b2a7" ON "mga_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f533380b769f800d1492105e3" ON "mga_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_7117ee71cc218415f2be46a6a3" ON "reinsurer_companies" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_636f3b23699316e79d35d343e1" ON "reinsurer_companies" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b712096dcaee62ca2ebbad48a" ON "carriers" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_51875971b77238085f928bbff4" ON "carriers" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_06f25c63f46865f24cca1598ce" ON "lines_of_business" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_730aad578e91a53596f0fc8ee2" ON "lines_of_business" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_b60f6e2ac8dccb9b6d29b796da" ON "cob_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac39d01d81270f0ad5bde32c66" ON "cob_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_339070276ba9fe90b2728146be" ON "treaty_lob_cobs" ("treaty_lob_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_35b5ca41780bb232da4e52840c" ON "treaty_lob_cobs" ("cob_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_77c8a64b1afad267e5d4df1358" ON "treaty_lobs" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5cc81eb0a8d7c72c36013590a" ON "treaty_lobs" ("lob_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4c967307c19e0b105798cedb4" ON "state_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8edc19ffd81e8ca3f2c13fa15" ON "state_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d6d5497e0a578007348788c2a" ON "treaty_states" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e730192bcedd292def00db350" ON "treaty_states" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9bedd08208ec57db492d0f4004" ON "treaty_mgas" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_61cbb5d34914c8e8ed97ce1aa8" ON "treaty_mgas" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a380bf2ed4f746522e8f8d9185" ON "broker_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_790e3c75e6d847709063e7c453" ON "broker_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e34e3987ef45da0f55edf494a" ON "treaty_state_carriers" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7eea07b0b57b75e2a7a00e2213" ON "treaty_state_carriers" ("risk_company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa2313934b90a8858d6ac19617" ON "treaty_state_carriers" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_062775d98e5080bf4d2d5cab68" ON "treaty_state_carriers" ("broker_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca593ab9fd3e462a7330173f1a" ON "treaty_state_carriers" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_45d0b4ac835a933c29e2cf5469" ON "treaty_reinsurers" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_89cc1d82dbab33eb68c7f39504" ON "treaty_reinsurers" ("reinsurer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_57a7e88bcd24145391ca38d3e9" ON "treaty_reinsurers" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_38f27e51ca25957a46ed905a98" ON "treaty_reinsurers" ("broker_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7c94d27a65f232ff88ffb470f" ON "treaties" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_227ea000eb9c328e64cc79fc80" ON "treaties" ("reinsurer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cb77ced5a092aa8f5e4377e11" ON "treaties" ("risk_company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5240ba827d7c37224c0181569" ON "treaties" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_9477f5df81ffa6478a28be9d76" ON "treaties" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7270f52b5fa6336bb465629e7" ON "treaty_type_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e4752ed8f13abc7520326b4f6" ON "treaty_type_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ad25c915924963a7afb133a3e" ON "treaty_products" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c031fd54c41df653abfcad1d74" ON "treaty_products" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9fa48624e591fad6e68f15cb1" ON "treaty_products" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e0b8a1bc5cb9be7aa85b6dec5" ON "treaty_sequence_prefixes" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_34dafee433bd280a40ea64ea17" ON "treaty_sequence_prefixes" ("sequence_prefix_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92806d6e6a5629e6db713bfb56" ON "treaty_sequence_prefixes" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c2c8c71c9bf9d8732bd7e9a65" ON "treaty_itd_totals" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcf34a01c1e28d198d9e3fe974" ON "treaty_itd_totals" ("year") `);
        await queryRunner.query(`CREATE INDEX "IDX_224d0c011d5a55c766bf47fd4f" ON "treaty_itd_totals" ("month") `);
        await queryRunner.query(`CREATE INDEX "IDX_beb950437e6be6cca0437b57ca" ON "treaty_itd_totals" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b7ae2faac96ebdcce75dc4ca5" ON "treaty_itd_totals" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_577c6aa69c19d6a05ffca9a3a7" ON "sequence_prefix_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_c00d35ade64fb9a984b85b1c92" ON "sequence_prefix_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_bde57dfc659f16df4c1644b7b5" ON "carrier_documents" ("risk_company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cb90c4ed66288c3da379b422f" ON "carrier_documents" ("document_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba21a28e143fd394b3e2f295cc" ON "carrier_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_7155d70022733f235f7295d720" ON "product_master" ("lob_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd254674561c941338f3d1615b" ON "product_master" ("cob_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1b7e875715ddfeec2b10ea9a6" ON "product_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ae0b90a226be4dc536acd3f95" ON "product_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa477ac8de064df6cb02e5dfea" ON "state_documents" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4ca639c9eb40f1650ebbc9d41" ON "state_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_597aaa11270e359c3c224604f9" ON "product_lobs" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_50b2d762f6ce4425e14052e477" ON "product_lobs" ("lob_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c04ebec51d405b3d313f3b53a2" ON "product_lobs" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_9419f87d116c1b34df57229e5b" ON "product_cobs" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7506ec04d832f6d82920b62be7" ON "product_cobs" ("cob_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a496fe8c356047716ae809a52" ON "product_cobs" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_85509651ab4744c3ead2a30194" ON "mga_other_names" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_44f42fd44e428fc8107624d8f4" ON "mga_other_names" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_767bf455b5d191e9a7eaa17721" ON "mga_documents" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2844f0156fa80802f52ae512e" ON "mga_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_41dbceb995b8753997cf9c13ca" ON "mga_contact_master" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d89102ebd85201c3064eb9514" ON "mga_contact_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e006440fa21890374b2271833" ON "mga_contact_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_cabb1cc2ca0e9708cf2cebb7a0" ON "locked_periods" ("is_locked") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdd6f47bd9c3e881078015e081" ON "locked_periods" ("locked_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_af9b55430b99c1c3218330a393" ON "document_type_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1fdc69895cbed76cbac5cd8c7f" ON "document_type_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_cddd69b5263a0d572f9fc08f34" ON "contact_domain_master" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a3ddfe89d580be7cf458e5076" ON "contact_domain_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_127448d8b02439b49fd48e917d" ON "contact_domain_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e6cccde15e19d8ffccd974a1c" ON "broker_documents" ("broker_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fef1af83a8efc498d17ff8e89e" ON "broker_documents" ("document_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4334164a88139e52ae2b8abc75" ON "broker_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_9274c87b73c76a37f72a1f7e8b" ON "journal_entry_batches" ("period") `);
        await queryRunner.query(`CREATE INDEX "IDX_2add1786a80f24415315642a1b" ON "journal_entry_batches" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_504feaad916b3fe4e7f6cb2096" ON "journal_entry_batches" ("month_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_66b0accc85d3b780954d222c81" ON "journal_entry_batches" ("workbook_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa5cf2bbbc93cdd209d32e174a" ON "journal_entry_batches" ("state_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e52a7252638ce11dfc7268986" ON "journal_entry_batches" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7902595e6e2c9926460f8919f" ON "journal_entry_batches" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_233c2a470511f11b1564bb6cd1" ON "chart_of_accounts" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2421e464a281cc019534ddd563" ON "chart_of_accounts" ("earning_account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e0b6959c158ad235bd48e3bb8" ON "chart_of_accounts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_35aa40590eaa109077a8432bd4" ON "chart_of_accounts" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e5d46369ee0b9de3a24c23bb9" ON "journal_entries" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c23b37139aba44dd3730e7c88c" ON "journal_entries" ("coa_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a60ea60964189a5a56f07dc8dc" ON "journal_entries" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_959282a750ba9f90e0b5301580" ON "journal_entry_drafts" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_182b5dc2f66a8ee435501b4b9b" ON "journal_entry_drafts" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_0eb6769f0bb0799ffe4704222d" ON "gl_mappings" ("coa_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c622646149f5d8c38b6b226b8" ON "gl_mappings" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fb23c3b101c6dad9df11dff98" ON "chart_of_account_documents" ("coa_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_692406da0819ce7a6326597c45" ON "chart_of_account_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_d54f841fa5478e4734590d4403" ON "activity_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b38bdabb0ea236c2836a79c4d1" ON "activity_logs" ("module_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb6adcbf1da4881b2a2a86ba41" ON "activity_logs" ("submodule_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_879e2d305a025dadfe9929c47d" ON "activity_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_09121048ab4513dbd4545074ce" ON "activity_logs" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd64e0e98220d39e897f3d3e3e" ON "activity_logs" ("entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1fa31efc2a0bc0b517b9f7225d" ON "activity_logs" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "treaty_lob_cobs" ADD CONSTRAINT "UQ_b62375077234ab363a10c461887" UNIQUE ("treaty_lob_id", "cob_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_lobs" ADD CONSTRAINT "UQ_96ef6e50436876b24e98a85f961" UNIQUE ("treaty_id", "lob_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_states" ADD CONSTRAINT "UQ_fa99ef4370b664c1bac21cb457e" UNIQUE ("treaty_id", "state_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_mgas" ADD CONSTRAINT "UQ_cbbda12b4f7b8a3cb141bae9f4c" UNIQUE ("treaty_id", "mga_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_products" ADD CONSTRAINT "UQ_5f1964b6e299dc033cbe3944013" UNIQUE ("treaty_id", "product_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_itd_totals" ADD CONSTRAINT "UQ_82b14298d258ee3bdd02b67dbe0" UNIQUE ("treaty_id", "state_id", "year", "month")`);
        await queryRunner.query(`ALTER TABLE "product_lobs" ADD CONSTRAINT "UQ_315a444ab4b5fc491654e20b633" UNIQUE ("product_id", "lob_id")`);
        await queryRunner.query(`ALTER TABLE "product_cobs" ADD CONSTRAINT "UQ_ca2e5a18a782568bb8cee0c8f80" UNIQUE ("product_id", "cob_id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_cobs" DROP CONSTRAINT "UQ_ca2e5a18a782568bb8cee0c8f80"`);
        await queryRunner.query(`ALTER TABLE "product_lobs" DROP CONSTRAINT "UQ_315a444ab4b5fc491654e20b633"`);
        await queryRunner.query(`ALTER TABLE "treaty_itd_totals" DROP CONSTRAINT "UQ_82b14298d258ee3bdd02b67dbe0"`);
        await queryRunner.query(`ALTER TABLE "treaty_products" DROP CONSTRAINT "UQ_5f1964b6e299dc033cbe3944013"`);
        await queryRunner.query(`ALTER TABLE "treaty_mgas" DROP CONSTRAINT "UQ_cbbda12b4f7b8a3cb141bae9f4c"`);
        await queryRunner.query(`ALTER TABLE "treaty_states" DROP CONSTRAINT "UQ_fa99ef4370b664c1bac21cb457e"`);
        await queryRunner.query(`ALTER TABLE "treaty_lobs" DROP CONSTRAINT "UQ_96ef6e50436876b24e98a85f961"`);
        await queryRunner.query(`ALTER TABLE "treaty_lob_cobs" DROP CONSTRAINT "UQ_b62375077234ab363a10c461887"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fa31efc2a0bc0b517b9f7225d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd64e0e98220d39e897f3d3e3e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09121048ab4513dbd4545074ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_879e2d305a025dadfe9929c47d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb6adcbf1da4881b2a2a86ba41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b38bdabb0ea236c2836a79c4d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d54f841fa5478e4734590d4403"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692406da0819ce7a6326597c45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fb23c3b101c6dad9df11dff98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c622646149f5d8c38b6b226b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0eb6769f0bb0799ffe4704222d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_182b5dc2f66a8ee435501b4b9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_959282a750ba9f90e0b5301580"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a60ea60964189a5a56f07dc8dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c23b37139aba44dd3730e7c88c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e5d46369ee0b9de3a24c23bb9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35aa40590eaa109077a8432bd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e0b6959c158ad235bd48e3bb8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2421e464a281cc019534ddd563"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_233c2a470511f11b1564bb6cd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7902595e6e2c9926460f8919f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e52a7252638ce11dfc7268986"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa5cf2bbbc93cdd209d32e174a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66b0accc85d3b780954d222c81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_504feaad916b3fe4e7f6cb2096"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2add1786a80f24415315642a1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9274c87b73c76a37f72a1f7e8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4334164a88139e52ae2b8abc75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fef1af83a8efc498d17ff8e89e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e6cccde15e19d8ffccd974a1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_127448d8b02439b49fd48e917d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a3ddfe89d580be7cf458e5076"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cddd69b5263a0d572f9fc08f34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fdc69895cbed76cbac5cd8c7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af9b55430b99c1c3218330a393"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdd6f47bd9c3e881078015e081"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cabb1cc2ca0e9708cf2cebb7a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e006440fa21890374b2271833"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d89102ebd85201c3064eb9514"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41dbceb995b8753997cf9c13ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2844f0156fa80802f52ae512e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_767bf455b5d191e9a7eaa17721"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44f42fd44e428fc8107624d8f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85509651ab4744c3ead2a30194"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a496fe8c356047716ae809a52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7506ec04d832f6d82920b62be7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9419f87d116c1b34df57229e5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c04ebec51d405b3d313f3b53a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50b2d762f6ce4425e14052e477"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_597aaa11270e359c3c224604f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4ca639c9eb40f1650ebbc9d41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa477ac8de064df6cb02e5dfea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ae0b90a226be4dc536acd3f95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1b7e875715ddfeec2b10ea9a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd254674561c941338f3d1615b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7155d70022733f235f7295d720"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba21a28e143fd394b3e2f295cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cb90c4ed66288c3da379b422f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bde57dfc659f16df4c1644b7b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c00d35ade64fb9a984b85b1c92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_577c6aa69c19d6a05ffca9a3a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b7ae2faac96ebdcce75dc4ca5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beb950437e6be6cca0437b57ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_224d0c011d5a55c766bf47fd4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcf34a01c1e28d198d9e3fe974"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c2c8c71c9bf9d8732bd7e9a65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92806d6e6a5629e6db713bfb56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34dafee433bd280a40ea64ea17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e0b8a1bc5cb9be7aa85b6dec5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9fa48624e591fad6e68f15cb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c031fd54c41df653abfcad1d74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ad25c915924963a7afb133a3e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e4752ed8f13abc7520326b4f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7270f52b5fa6336bb465629e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9477f5df81ffa6478a28be9d76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5240ba827d7c37224c0181569"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cb77ced5a092aa8f5e4377e11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_227ea000eb9c328e64cc79fc80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7c94d27a65f232ff88ffb470f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38f27e51ca25957a46ed905a98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57a7e88bcd24145391ca38d3e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89cc1d82dbab33eb68c7f39504"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45d0b4ac835a933c29e2cf5469"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca593ab9fd3e462a7330173f1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_062775d98e5080bf4d2d5cab68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa2313934b90a8858d6ac19617"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7eea07b0b57b75e2a7a00e2213"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e34e3987ef45da0f55edf494a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_790e3c75e6d847709063e7c453"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a380bf2ed4f746522e8f8d9185"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61cbb5d34914c8e8ed97ce1aa8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bedd08208ec57db492d0f4004"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e730192bcedd292def00db350"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d6d5497e0a578007348788c2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8edc19ffd81e8ca3f2c13fa15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4c967307c19e0b105798cedb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5cc81eb0a8d7c72c36013590a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77c8a64b1afad267e5d4df1358"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35b5ca41780bb232da4e52840c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_339070276ba9fe90b2728146be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac39d01d81270f0ad5bde32c66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b60f6e2ac8dccb9b6d29b796da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_730aad578e91a53596f0fc8ee2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06f25c63f46865f24cca1598ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51875971b77238085f928bbff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b712096dcaee62ca2ebbad48a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_636f3b23699316e79d35d343e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7117ee71cc218415f2be46a6a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f533380b769f800d1492105e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc99b625341e8f9273fb74b2a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3deea0a3e5e072a75d88425dbf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45bb6d028c873f68369b3e8be8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8145f5fadacd311693c15e41f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b987cb1236bbe09f8f448ee059"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ab0433089f0b41a0f8e5b10d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3495bd31f1862d02931e8e8d2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd91d7b4b599ee5211d603ccfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3676155292d72c67cd4e090514"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2cecd1a3531c0b041e29ba46e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c3f678dd1e8eacf8d39da5913"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95781bd52e5eee5ac8b3e54d67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de92ecfd812c5ce8782c9922d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fd56ae8b1051642d5f051c3eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab6380bd0d8f038a5ee931ac76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3c01743a846289d1192f752be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c2912eb0a6ef3a75578177ac3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db57e595c744ed4a1da36ce424"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cbdddc932e472bfacf5eb59b8"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "correlation_id"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "session_id"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "browser"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "os"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "device"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "product_cobs" ADD CONSTRAINT "uq_product_cobs_product_id_cob_id" UNIQUE ("product_id", "cob_id")`);
        await queryRunner.query(`ALTER TABLE "product_lobs" ADD CONSTRAINT "uq_product_lobs_product_id_lob_id" UNIQUE ("product_id", "lob_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_itd_totals" ADD CONSTRAINT "uq_treaty_itd_totals_treaty_id_state_id_year_month" UNIQUE ("treaty_id", "year", "month", "state_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_products" ADD CONSTRAINT "uq_treaty_products_treaty_id_product_id" UNIQUE ("treaty_id", "product_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_mgas" ADD CONSTRAINT "uq_treaty_mgas_treaty_id_mga_id" UNIQUE ("treaty_id", "mga_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_states" ADD CONSTRAINT "uq_treaty_states_treaty_id_state_id" UNIQUE ("treaty_id", "state_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_lobs" ADD CONSTRAINT "uq_treaty_lobs_treaty_id_lob_id" UNIQUE ("treaty_id", "lob_id")`);
        await queryRunner.query(`ALTER TABLE "treaty_lob_cobs" ADD CONSTRAINT "uq_treaty_lob_cobs_treaty_lob_id_cob_id" UNIQUE ("treaty_lob_id", "cob_id")`);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_created_at" ON "activity_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_entity_id" ON "activity_logs" ("entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_entity_type" ON "activity_logs" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_action" ON "activity_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_submodule_id" ON "activity_logs" ("submodule_id") `);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_module_id" ON "activity_logs" ("module_id") `);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_user_id" ON "activity_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_chart_of_account_documents_is_deleted" ON "chart_of_account_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_chart_of_account_documents_coa_id" ON "chart_of_account_documents" ("coa_id") `);
        await queryRunner.query(`CREATE INDEX "idx_gl_mappings_is_deleted" ON "gl_mappings" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_gl_mappings_coa_id" ON "gl_mappings" ("coa_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_drafts_is_deleted" ON "journal_entry_drafts" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_drafts_batch_id" ON "journal_entry_drafts" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entries_date" ON "journal_entries" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entries_coa_id" ON "journal_entries" ("coa_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entries_batch_id" ON "journal_entries" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_chart_of_accounts_is_deleted" ON "chart_of_accounts" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_chart_of_accounts_is_active" ON "chart_of_accounts" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_chart_of_accounts_earning_account_id" ON "chart_of_accounts" ("earning_account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_chart_of_accounts_parent_id" ON "chart_of_accounts" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_batches_is_deleted" ON "journal_entry_batches" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_batches_period" ON "journal_entry_batches" ("period") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_batches_status" ON "journal_entry_batches" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_batches_state_code" ON "journal_entry_batches" ("state_code") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_batches_workbook_id" ON "journal_entry_batches" ("workbook_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_batches_month_key" ON "journal_entry_batches" ("month_key") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_entry_batches_treaty_id" ON "journal_entry_batches" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_broker_documents_is_deleted" ON "broker_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_broker_documents_document_type_id" ON "broker_documents" ("document_type_id") `);
        await queryRunner.query(`CREATE INDEX "idx_broker_documents_broker_id" ON "broker_documents" ("broker_id") `);
        await queryRunner.query(`CREATE INDEX "idx_contact_domain_master_is_deleted" ON "contact_domain_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_contact_domain_master_is_active" ON "contact_domain_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_contact_domain_master_mga_id" ON "contact_domain_master" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "idx_document_type_master_is_deleted" ON "document_type_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_document_type_master_is_active" ON "document_type_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_locked_periods_locked_by" ON "locked_periods" ("locked_by") `);
        await queryRunner.query(`CREATE INDEX "idx_locked_periods_is_locked" ON "locked_periods" ("is_locked") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_contact_master_is_deleted" ON "mga_contact_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_contact_master_is_active" ON "mga_contact_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_contact_master_mga_id" ON "mga_contact_master" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_documents_is_deleted" ON "mga_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_documents_mga_id" ON "mga_documents" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_other_names_is_deleted" ON "mga_other_names" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_other_names_mga_id" ON "mga_other_names" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_cobs_is_deleted" ON "product_cobs" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_product_cobs_cob_id" ON "product_cobs" ("cob_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_cobs_product_id" ON "product_cobs" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_lobs_is_deleted" ON "product_lobs" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_product_lobs_lob_id" ON "product_lobs" ("lob_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_lobs_product_id" ON "product_lobs" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_state_documents_is_deleted" ON "state_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_state_documents_state_id" ON "state_documents" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_master_is_deleted" ON "product_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_product_master_is_active" ON "product_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_product_master_cob_id" ON "product_master" ("cob_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_master_lob_id" ON "product_master" ("lob_id") `);
        await queryRunner.query(`CREATE INDEX "idx_carrier_documents_is_deleted" ON "carrier_documents" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_carrier_documents_document_type_id" ON "carrier_documents" ("document_type_id") `);
        await queryRunner.query(`CREATE INDEX "idx_carrier_documents_risk_company_id" ON "carrier_documents" ("risk_company_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sequence_prefix_master_is_deleted" ON "sequence_prefix_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_sequence_prefix_master_is_active" ON "sequence_prefix_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_itd_totals_is_deleted" ON "treaty_itd_totals" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_itd_totals_state_id" ON "treaty_itd_totals" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_itd_totals_month" ON "treaty_itd_totals" ("month") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_itd_totals_year" ON "treaty_itd_totals" ("year") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_itd_totals_treaty_id" ON "treaty_itd_totals" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_sequence_prefixes_is_deleted" ON "treaty_sequence_prefixes" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_sequence_prefixes_sequence_prefix_id" ON "treaty_sequence_prefixes" ("sequence_prefix_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_sequence_prefixes_treaty_id" ON "treaty_sequence_prefixes" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_products_is_deleted" ON "treaty_products" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_products_product_id" ON "treaty_products" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_products_treaty_id" ON "treaty_products" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_type_master_is_deleted" ON "treaty_type_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_type_master_is_active" ON "treaty_type_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_treaties_is_deleted" ON "treaties" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_treaties_is_active" ON "treaties" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_treaties_risk_company_id" ON "treaties" ("risk_company_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaties_reinsurer_id" ON "treaties" ("reinsurer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaties_mga_id" ON "treaties" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_reinsurers_broker_id" ON "treaty_reinsurers" ("broker_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_reinsurers_state_id" ON "treaty_reinsurers" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_reinsurers_reinsurer_id" ON "treaty_reinsurers" ("reinsurer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_reinsurers_treaty_id" ON "treaty_reinsurers" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_state_carriers_is_deleted" ON "treaty_state_carriers" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_state_carriers_broker_id" ON "treaty_state_carriers" ("broker_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_state_carriers_state_id" ON "treaty_state_carriers" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_state_carriers_risk_company_id" ON "treaty_state_carriers" ("risk_company_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_state_carriers_treaty_id" ON "treaty_state_carriers" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_broker_master_is_deleted" ON "broker_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_broker_master_is_active" ON "broker_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_mgas_mga_id" ON "treaty_mgas" ("mga_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_mgas_treaty_id" ON "treaty_mgas" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_states_state_id" ON "treaty_states" ("state_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_states_treaty_id" ON "treaty_states" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_state_master_is_deleted" ON "state_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_state_master_is_active" ON "state_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_lobs_lob_id" ON "treaty_lobs" ("lob_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_lobs_treaty_id" ON "treaty_lobs" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_lob_cobs_cob_id" ON "treaty_lob_cobs" ("cob_id") `);
        await queryRunner.query(`CREATE INDEX "idx_treaty_lob_cobs_treaty_lob_id" ON "treaty_lob_cobs" ("treaty_lob_id") `);
        await queryRunner.query(`CREATE INDEX "idx_cob_master_is_deleted" ON "cob_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_cob_master_is_active" ON "cob_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_lines_of_business_is_deleted" ON "lines_of_business" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_lines_of_business_is_active" ON "lines_of_business" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_carriers_is_deleted" ON "carriers" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_carriers_is_active" ON "carriers" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_reinsurer_companies_is_deleted" ON "reinsurer_companies" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_reinsurer_companies_is_active" ON "reinsurer_companies" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_master_is_deleted" ON "mga_master" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_mga_master_is_active" ON "mga_master" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_calculation_report_lines_is_deleted" ON "calculation_report_lines" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_calculation_report_lines_treaty_id" ON "calculation_report_lines" ("treaty_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_permissions_permission_id" ON "user_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_permissions_submodule_id" ON "user_permissions" ("submodule_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_permissions_module_id" ON "user_permissions" ("module_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_permissions_user_id" ON "user_permissions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_is_deleted" ON "users" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "idx_users_status" ON "users" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role_id" ON "users" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workbooks_is_deleted" ON "workbooks" ("isDeleted") `);
        await queryRunner.query(`CREATE INDEX "idx_workbooks_status" ON "workbooks" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_workbooks_month_key" ON "workbooks" ("monthKey") `);
        await queryRunner.query(`CREATE INDEX "idx_cash_settlements_is_deleted" ON "cash_settlements" ("isDeleted") `);
        await queryRunner.query(`CREATE INDEX "idx_cash_settlements_reinsurer_id" ON "cash_settlements" ("reinsurer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_cash_settlements_batch_id" ON "cash_settlements" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "idx_state_exhibits_is_deleted" ON "state_exhibits" ("isDeleted") `);
        await queryRunner.query(`CREATE INDEX "idx_state_exhibits_state_code" ON "state_exhibits" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "idx_state_exhibits_workbook_id" ON "state_exhibits" ("workbookId") `);
    }

}
