import { Injectable, BadRequestException } from '@nestjs/common';
import { JournalEntry } from '../../journal-entries/entities/journal-entry.entity';
import { WorkbooksService } from '../../workbook/workbooks/workbooks.service';
import { ReinsuranceStatementService } from '../reinsurance-statement/reinsurance-statement.service';
import { GlJournalEntriesDao } from './dao/gl-journal-entries.dao';

type CedingValues = ReturnType<ReinsuranceStatementService['calculateCedingValues']>;

interface GlMappingSchema {
  desc: string;
  account: string;
  cc: string;
  mga: string;
  lob: string;
  st: string;
  ext: string;
  sub: string;
  lineDesc: string;
  formula: (vals: CedingValues) => number;
  formulaStr: string;
}

export interface GlJournalEntryRow {
  desc: string;
  comp: string;
  account: string;
  cc: string;
  mga: string;
  lob: string;
  st: string;
  ext: string;
  sub: string;
  lineDesc: string;
  debit: number;
  credit: number;
  formula: string;
}

/** Generates GL journal entry rows from reinsurance ceding values and posts them into journal entry batches. */
@Injectable()
export class GlJournalEntriesService {
  constructor(
    private readonly dao: GlJournalEntriesDao,
    private readonly workbooksService: WorkbooksService,
    private readonly reinsuranceStatementService: ReinsuranceStatementService,
  ) {}

  async getGLJournalEntries(workbookId: number, stateCode: string): Promise<GlJournalEntryRow[]> {
    const workbook = await this.workbooksService.findOne(workbookId);
    const prevStateEx = await this.reinsuranceStatementService.getPreviousStateExhibit(
      workbook,
      stateCode,
    );
    const v = this.reinsuranceStatementService.calculateCedingValues(
      workbook,
      stateCode,
      prevStateEx,
    );

    const GL_MAPPING_SCHEMA_TEMPLATE: GlMappingSchema[] = [
      {
        desc: 'Uncollected Premium Direct',
        account: '120100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.premiumWritten,
        formulaStr: 'Premiums Written',
      },
      {
        desc: 'Direct Premium Written',
        account: '400100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.premiumWritten,
        formulaStr: '-Direct Premium Written',
      },
      {
        desc: 'Change in Unearned Premium Direct',
        account: '411100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeUEP,
        formulaStr: '-Change in UEP',
      },
      {
        desc: 'Unearned Premium Direct',
        account: '230100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeUEP,
        formulaStr: 'Change in UEP',
      },
      {
        desc: 'Ceded Premium Written',
        account: '400300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.premiumWritten,
        formulaStr: 'Premiums Written',
      },
      {
        desc: 'Ceded Reinsurance Premiums Payable',
        account: '243100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.premiumWritten,
        formulaStr: '-Premiums Written',
      },
      {
        desc: 'Unearned Premium Ceded',
        account: '230300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeUEP,
        formulaStr: '-Change in UEP',
      },
      {
        desc: 'Change in Unearned Premium Ceded',
        account: '411300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeUEP,
        formulaStr: 'Change in UEP',
      },
      {
        desc: 'Commissions Direct',
        account: '500100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.cedingCommission,
        formulaStr: 'Ceding Commissions',
      },
      {
        desc: 'Uncollected Premium Direct',
        account: '120100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.cedingCommission,
        formulaStr: '-Ceding Commissions',
      },
      {
        desc: 'Ceded Reinsurance Premiums Payable',
        account: '243100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.cedingCommission,
        formulaStr: 'Ceding Commissions',
      },
      {
        desc: 'Commissions Ceded',
        account: '500300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.cedingCommission,
        formulaStr: '-Ceding Commissions',
      },
      {
        desc: 'Direct Losses paid',
        account: '600100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.lossesPaid,
        formulaStr: 'Losses Paid',
      },
      {
        desc: 'Payable to MGA',
        account: '264400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.lossesPaid,
        formulaStr: '-Losses Paid',
      },
      {
        desc: 'Amounts recoverable from reinsurers',
        account: '125100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.lossesPaid,
        formulaStr: 'Losses Paid',
      },
      {
        desc: 'Ceded Losses Paid',
        account: '600300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.lossesPaid,
        formulaStr: '-Losses Paid',
      },
      {
        desc: 'Change in Case Loss Reserves - Direct',
        account: '550100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeLossReserves,
        formulaStr: 'Change in Loss Reserves',
      },
      {
        desc: 'Case Loss Reserves - Direct',
        account: '200100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeLossReserves,
        formulaStr: '-Change in Loss Reserves',
      },
      {
        desc: 'Case Loss Reserves - Ceded',
        account: '200300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeLossReserves,
        formulaStr: 'Change in Loss Reserves',
      },
      {
        desc: 'Change in Case Loss Reserves - Ceded',
        account: '550300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeLossReserves,
        formulaStr: '-Change in Loss Reserves',
      },
      {
        desc: 'Change in IBNR Loss Reserves - Direct',
        account: '550400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeLossIBNR,
        formulaStr: 'Change in Loss IBNR',
      },
      {
        desc: 'IBNR Loss Reserves - Direct',
        account: '200400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeLossIBNR,
        formulaStr: '-Change in Loss IBNR',
      },
      {
        desc: 'IBNR Loss Reserves - Ceded',
        account: '200600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeLossIBNR,
        formulaStr: 'Change in Loss IBNR',
      },
      {
        desc: 'Change in IBNR Loss Reserves - Ceded',
        account: '550600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeLossIBNR,
        formulaStr: '-Change in Loss IBNR',
      },
      {
        desc: 'Direct LAE DCC Paid',
        account: '601100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.dccPaid,
        formulaStr: 'DCC Paid',
      },
      {
        desc: 'Payable to MGA',
        account: '264400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.dccPaid,
        formulaStr: '-DCC Paid',
      },
      {
        desc: 'Amounts recoverable from reinsurers',
        account: '125100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.dccPaid,
        formulaStr: 'DCC Paid',
      },
      {
        desc: 'Ceded LAE DCC Paid',
        account: '601300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.dccPaid,
        formulaStr: '-DCC Paid',
      },
      {
        desc: 'Change in LAE DCC Reserves - Direct',
        account: '557100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeDCCReserves,
        formulaStr: 'Change in DCC Reserves',
      },
      {
        desc: 'LAE DCC Reserves - Direct',
        account: '207100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeDCCReserves,
        formulaStr: '-Change in DCC Reserves',
      },
      {
        desc: 'LAE DCC Reserves - Ceded',
        account: '207300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeDCCReserves,
        formulaStr: 'Change in DCC Reserves',
      },
      {
        desc: 'Change in LAE DCC Reserves - Ceded',
        account: '557300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeDCCReserves,
        formulaStr: '-Change in DCC Reserves',
      },
      {
        desc: 'Change in IBNR DCC Reserves - Direct',
        account: '557400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeDCCIBNR,
        formulaStr: 'Change in DCC IBNR',
      },
      {
        desc: 'IBNR DCC Reserves - Direct',
        account: '207400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeDCCIBNR,
        formulaStr: '-Change in DCC IBNR',
      },
      {
        desc: 'IBNR DCC Reserves - Ceded',
        account: '207600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeDCCIBNR,
        formulaStr: 'Change in DCC IBNR',
      },
      {
        desc: 'Change in IBNR DCC Reserves - Ceded',
        account: '557600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeDCCIBNR,
        formulaStr: '-Change in DCC IBNR',
      },
      {
        desc: 'Direct LAE A&O Paid',
        account: '602100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.aoePaid,
        formulaStr: 'AOE Paid',
      },
      {
        desc: 'Payable to MGA',
        account: '264400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.aoePaid,
        formulaStr: '-AOE Paid',
      },
      {
        desc: 'Amounts recoverable from reinsurers',
        account: '125100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.aoePaid,
        formulaStr: 'AOE Paid',
      },
      {
        desc: 'Ceded LAE A&O Paid',
        account: '602300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.aoePaid,
        formulaStr: '-AOE Paid',
      },
      {
        desc: 'Change in LAE A&O Reserves - Direct',
        account: '558100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeAOEReserves,
        formulaStr: 'Change in AOE Reserves',
      },
      {
        desc: 'LAE A&O Reserves - Direct',
        account: '208100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeAOEReserves,
        formulaStr: '-Change in AOE Reserves',
      },
      {
        desc: 'LAE A&O Reserves - Ceded',
        account: '208300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeAOEReserves,
        formulaStr: 'Change in AOE Reserves',
      },
      {
        desc: 'Change in LAE A&O Reserves - Ceded',
        account: '558300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeAOEReserves,
        formulaStr: '-Change in AOE Reserves',
      },
      {
        desc: 'Change in IBNR A&O Reserves - Direct',
        account: '558400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeAOEIBNR,
        formulaStr: 'Change in AOE IBNR',
      },
      {
        desc: 'IBNR A&O Reserves - Direct',
        account: '208400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeAOEIBNR,
        formulaStr: '-Change in AOE IBNR',
      },
      {
        desc: 'IBNR A&O Reserves - Ceded',
        account: '208600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeAOEIBNR,
        formulaStr: 'Change in AOE IBNR',
      },
      {
        desc: 'Change in IBNR A&O Reserves - Ceded',
        account: '558600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeAOEIBNR,
        formulaStr: '-Change in AOE IBNR',
      },
      {
        desc: 'Direct ULAE Paid',
        account: '603100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.ulaePaid,
        formulaStr: 'ULAE Paid',
      },
      {
        desc: 'Payable to MGA',
        account: '264400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.ulaePaid,
        formulaStr: '-ULAE Paid',
      },
      {
        desc: 'Amounts recoverable from reinsurers',
        account: '125100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.ulaePaid,
        formulaStr: 'ULAE Paid',
      },
      {
        desc: 'Ceded ULAE Paid',
        account: '603300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.ulaePaid,
        formulaStr: '-ULAE Paid',
      },
      {
        desc: 'Change in IBNR ULAE Reserves - Direct',
        account: '559400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeULAEIBNR,
        formulaStr: 'Change in ULAE IBNR',
      },
      {
        desc: 'IBNR ULAE Reserves - Direct',
        account: '209400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeULAEIBNR,
        formulaStr: '-Change in ULAE IBNR',
      },
      {
        desc: 'IBNR ULAE Reserves - Ceded',
        account: '209600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.changeULAEIBNR,
        formulaStr: 'Change in ULAE IBNR',
      },
      {
        desc: 'Change in IBNR ULAE Reserves - Ceded',
        account: '559600',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.changeULAEIBNR,
        formulaStr: '-Change in ULAE IBNR',
      },
      {
        desc: 'Other amounts recoverable from reinsurers',
        account: '127100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.boardsCharge,
        formulaStr: 'Boards Charge',
      },
      {
        desc: 'Commissions Ceded',
        account: '500300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.boardsCharge,
        formulaStr: '-Boards Charge',
      },
      {
        desc: 'Commissions Ceded',
        account: '500300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.boardsUEP,
        formulaStr: '-Boards UEP',
      },
      {
        desc: 'Deferred Ceding Commissions',
        account: '243200',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.boardsUEP,
        formulaStr: 'Boards UEP',
      },
      {
        desc: 'Ceded Reinsurance Premiums Payable',
        account: '243100',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.lossRatioCap,
        formulaStr: 'Loss Ratio Cap Charge',
      },
      {
        desc: 'Commissions Ceded',
        account: '500300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.lossRatioCap,
        formulaStr: '-Loss Ratio Cap Charge',
      },
      {
        desc: 'Commissions Ceded',
        account: '500300',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.lossRatioCapUEP,
        formulaStr: '-Loss Ratio Cap UEP',
      },
      {
        desc: 'Deferred Ceding Commissions',
        account: '243200',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.lossRatioCapUEP,
        formulaStr: 'Loss Ratio Cap UEP',
      },
      {
        desc: 'Receivable from MGA',
        account: '160400',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.frontingFee,
        formulaStr: 'Fronting Fee',
      },
      {
        desc: 'Fronting Fees',
        account: '500110',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.frontingFee,
        formulaStr: '-Fronting Fee',
      },
      {
        desc: 'Fronting Fees',
        account: '500110',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: 'state',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => -vals.frontingFeeUEP,
        formulaStr: '-Fronting Fee UEP',
      },
      {
        desc: 'Deferred Ceding Commissions',
        account: '243200',
        cc: workbook.cc,
        mga: workbook.mga,
        lob: workbook.lob,
        st: '00',
        ext: workbook.ext,
        sub: workbook.sub,
        lineDesc: workbook.lineDescSuffix,
        formula: (vals: CedingValues) => vals.frontingFeeUEP,
        formulaStr: 'Fronting Fee UEP',
      },
    ];

    const rows: GlJournalEntryRow[] = [];
    GL_MAPPING_SCHEMA_TEMPLATE.forEach(schema => {
      let val = schema.formula(v);
      val = Math.round(val * 100) / 100;
      if (val === 0) return;

      const st = schema.st === 'state' ? stateCode : schema.st;

      rows.push({
        desc: schema.desc,
        comp: workbook.comp,
        account: schema.account,
        cc: schema.cc,
        mga: schema.mga,
        lob: schema.lob,
        st,
        ext: schema.ext,
        sub: schema.sub,
        lineDesc: schema.lineDesc,
        debit: val > 0 ? val : 0,
        credit: val < 0 ? Math.abs(val) : 0,
        formula: schema.formulaStr,
      });
    });
    return rows;
  }

  async postToJournalEntries(
    workbookId: number,
    stateCode: string,
    userId?: string,
    customRows?: GlJournalEntryRow[],
  ) {
    const workbook = await this.workbooksService.findOne(workbookId);
    const locked = await this.dao.findLockedPeriod(workbook.monthLabel);
    if (locked) {
      throw new BadRequestException(
        `Accounting period '${workbook.monthLabel}' is locked. Cannot post entries.`,
      );
    }
    let glRows = await this.getGLJournalEntries(workbookId, stateCode);

    if (customRows && Array.isArray(customRows)) {
      glRows = customRows;
    }

    if (glRows.length === 0) {
      throw new BadRequestException(
        'No journal entries generated for this workbook/state combination.',
      );
    }

    await this.workbooksService.updateStatus(workbookId, 'Approved');

    const batchNumber = `RE-${workbook.id}-${stateCode.toUpperCase()}`;
    let batch = await this.dao.findBatchByBatchNumber(batchNumber);

    let agentName = workbook.program;
    const treatyRows = await this.dao.queryTreatyMgaId(workbook.program);
    if (treatyRows && treatyRows.length > 0 && treatyRows[0].mga_id) {
      const mgaRows = await this.dao.queryMgaName(treatyRows[0].mga_id);
      if (mgaRows && mgaRows.length > 0) {
        agentName = mgaRows[0].name;
      }
    }

    if (batch) {
      await this.dao.deleteEntriesByBatchId(batch.id);
      batch.agentName = agentName;
      await this.dao.saveBatch(batch);
    } else {
      batch = this.dao.createBatch({
        batchNumber,
        period: workbook.monthLabel,
        agentName,
        totalAmount: 0,
        count: 0,
        createdBy: userId ?? null,
      });
      batch = await this.dao.saveBatch(batch);
    }

    const entries: JournalEntry[] = [];
    const today = new Date().toISOString().split('T')[0];
    const coaList = await this.dao.findAllChartOfAccounts();

    for (let i = 0; i < glRows.length; i++) {
      const row = glRows[i];
      const accountCodeNum = parseInt(row.account);
      const coa = coaList.find(c => c.accountCode === accountCodeNum);

      if (!coa) {
        throw new BadRequestException(
          `Chart of Account with code ${row.account} does not exist. Please seed it first.`,
        );
      }

      const entry = this.dao.createEntry({
        batchId: batch.id,
        jeNumber: 1,
        description: row.desc,
        coaId: coa.id,
        sub: row.sub ?? null,
        debit: row.debit > 0 ? row.debit : null,
        credit: row.credit > 0 ? row.credit : null,
        date: today,
        dp: '-',
        policy: row.lineDesc,
        memo: `Auto-generated from Reinsurance Statement ${workbook.program} ${workbook.monthLabel} (${stateCode})`,
      });
      entries.push(entry);
    }

    await this.dao.saveEntries(entries);

    const totalAmount = glRows.reduce((sum, r) => sum + Number(r.debit ?? 0), 0);
    batch.totalAmount = Math.round(totalAmount * 100) / 100;
    batch.count = 1;
    await this.dao.saveBatch(batch);

    return batch;
  }
}
